language: java
sudo: false
script: mvn clean install
notifications:
  email:
    recipients:
    - rakesh.kanchalwar@bitwiseglobal.com
  on_success: always
  on_failure: always
  cache: 
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: kcwJzGjiwaUcU8g32/5LKT7q8+pg6juczhdInTZUhgEJM66bCYYw6oViNEJ62dOXtSo+jdPDYs3wMhOJyBSM5FR5iUMyjtcJHtGYCxi6qjUlfdzwAPLUquYnIlfya2mO2uGUh3cjoJyUPilkpIiTRYLE/IHgUPBytRurBwGPsgyPPLezDpiVgZIl9au7UhPQXozuEZ92IgBySw7gXoomWPGB4yZWCwvZgRr0OdPO6YN/WLjAxm85AfGNs4EUxCn70bQ6YTQTjfXh6ReszpsphQV9nqoo9NTFMFRrAxj/Dw8oDVEmh6O50ISuCtjMYKgI+NcqZAP2LNnYhBw9nOxi2+8cTg/oLcFTTbSrzfTmQ3FsZtK4hI7666Cm/+0aDJ0LiETkTANtblrvqGVkTHc0ZSphF5bbERSQGOIVDx7NxkGfsqg5IAKJQopFOTLbEc9+5rgMBvAkdHXCN+9ZlI79/PY7bwzY8pfBAIUODPOoQ1DALDraUrX5k8MGafU+6Sw29RCUUH15NbBQURDuplnBHsu7D+/hrLjpHChmpWZfyOj59eEEUtyUaXihd8iv/B9se+JG2F4UP0xTyHDidywwYxt/L53gCrIXkz8MSEaKrGYsnD+Jb2+IT/SbfJY+ayKRdX7MXG+00zLTtXn1n//TOdCEGQKN+9xIYelcsHoxl6Q=
  - secure: qoVu9wupUGa26zZb5lbgjWc5vcKw7J0MZ33FZSZi5Q6pxamPxwmt+lHrgQXU85NeNOBmKXy8qN7yrBrlTX/GW8wJkahhLMv2JW1ZBDgnWSIGuu0Y6Vrb+GUTcK9FRNpmlgxTsZSpjaJKS+XgH1BLTzn5bapn6fgmS8ubuO1Rjy52wtR+cXBBml8ic6EXFkLO80o2kQnaPbwNBdt3D7DU9D8bX1fT/Qge/cCuSzqoh5RUX1/iaCJuLjpO9H3TohL2K/JBVcrdXbmqt024aX7vlPdttBemukoDSXdmGjAfIWcBbAUCjMO3oO0iIKHEn6/BHabZNSvKmNs5eWpsK2tKTYBcODuKRJvUxdLu1e8acWIj69hfKSvjaMTm9XTr2ym1sDyh1JzYsoz+hotH0vhtJ9MwH2TMATisfy3lxals+1zwiQXv4/0f5X+ePdeJNwYnFlH/0R38+QxYFHQ5Yn0OaXeyetaMW3Cny/tClnCGTTiuFOa1jt0fz8+P3BNLNuaLCYzmh25338nT7DXJIPxbKEW7K1xYYg9JWoLFqHKkfsvrf+pU2la9g78qPACI1ojtnbe0TNfc32ebJ7mJ+yEs6EjyiMo2RG2AEFyCKCaMc/ufX5zDDAUj26EUURPDx0Kqxxwv2vd/CMDBm4yWYbdw6GTui+RCzeX4lRGgNXYslNA=
after_success:
- curl --ftp-create-dirs -T /home/travis/build/rakeshkanchalwar/TestSpringBuild/target/Spring3Example-1.0-SNAPSHOT.jar  -u
  $FTP_USER:$FTP_PASSWORD ftp://ftp.bitwiseglobal.com:4469/$TRAVIS_JOB_NUMBER/
