language: java
sudo: false
script: mvn clean install
notifications:
  email:
    recipients:
    - rakesh.kanchalwar@bitwiseglobal.com
  on_success: always
  on_failure: always
  cache: 
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: "K7Qgh6/zdP77oiJRskoHVHklCrxSe7CbjxJwSLLo6VE50VKmlTo0eDpJlIH15ugHo4VICNuk7A47SE7JLa0CklBi5qrJAjfnvg7NqHK5w7oOl+JxJwMFGRv+i2flKn6UPirgIgkOJc/8zoH8RWtR6rq6BLLFN9t0goax0birAFe9S4StmipPtI1RbJneQzraoeckHtw4KYTnxVxBjd92XQRfYcyzzK4ky/LQHotsg1bgLIR5ZjPhHoHWMKFFP5vb/3VlGXr6I1+JFmMGn9FzhdWVX/GVaKHOg4fn8Rl1kD/7Klxqq1953C+RC/w4ZHQI1ds7KkLV8ihG3HxF1qLzt+R8x4HbbjEwxX0lIKHj2Ooo3/+EQ5D7CcX6hOcor8672kdMiZHXsCStsSqpp2qw7C1svadlFNOUXIRJQhyI0GRKeLA+6Cypxz7Q3uEqD45xV1RvkJ9KDg/0dB1/1Lt0wrF74X8V7eJuCEwXiPuQpgM4P0IT3L7Pf57bjg87yisw73QbO19nSvY+t0PGVmZfEmUdSr7LNA6vFNl0C/pgk1IcYkqRYh+S5lTl9PESxDqb9Kxrtw+ehaYuFqkAU5q+HFs4iPMIJJphuEAac31fE0xkJXen9XCESRgYlIz9T35H/GotM+wrUxU4sO53tZEXPsVxZT/idqgYnyQ13t4VJSo="
  - secure: "CpFd6redIQ9sbQADq7aAKsZMLEdo/KxC5bUOfnu4uZHZiIOOs8Toc5t3VzXmM5iz7+ncMddW0qKoADDR6LoXUCRfSdbVoe+ZTLR7mosXGj0AkYekd6tSOiglc6bAPddy4geSf+4Mme1z/Zki0pJJ481GXFCiEnd1M119zg5maTeh/NRt3RSikQddoKJKjRwtd0GFpVKDwddMM/jXIjL0Kb4dqRG49Eo7Sc3+js1j49t/PvQ9o317N4PNeNgap92DqPUFFu+44SdrfIcIVTB6l0MNBe8Yj2OaZHpR9HyEfnzYDDE2+HrfrqjlrXtTkfEDOGAk+q2X4r/xorkwEFVPwDUEUo3Vvv64MwzolPpxuylixul1ks6LgD0hgqjfshWbqpDDOC2aYZZcW3C44IlwiU6YxQaz2tSjISBHgdS+wbwElZTYDhIuHBbtXNpxy3KmZ0V+LTDvSYD+kjhRyJu9Ms7PDa18ZehSfRtGP5f30oWRJ+yT/AjfKvbE0SDtu8ptIRH73YZo2psfSddBgtAhcI22PmxSpTrTi120dsu+QGGERtrRCmc1N5fC850AoCdHcEtZcyagGkAPdAZ734P1ZeAazRnTdkrl6ihP75Ctfe8JGNa48E2bFnD/U1gl+5tjv6YQaeAsbFtSeTwluC/W8wGdZ2YmZyqYFvaBzUa0D80="
after_success:
- curl --ftp-create-dirs -T /home/travis/build/rakeshkanchalwar/TestSpringBuild/target/Spring3Example-1.0-SNAPSHOT.jar -u $FTP_USER:$FTP_PASSWORD ftp://ftp.bitwiseglobal.com:4469/$TRAVIS_JOB_NUMBER/

